### ISSUE TITLE
identical svg-files for yellow and red on https://lib.rs/crates/qute

### ISSUE THREAD

**Issue by Booze-Operator** [qurity/qute#1]
Sorry for the frugality of this issue, but I just noticed that on 
https://lib.rs/crates/qute
you use the very same svg-file to demonstrate yellow and red foreground-colors.

Put another way:
https://img.gs/czjpqfbdkz/full/https://raw.githubusercontent.com/qurity/qute/HEAD/doc/preview/hello-color-foreground-yellow.svg

is the same as

https://img.gs/czjpqfbdkz/full/https://raw.githubusercontent.com/qurity/qute/HEAD/doc/preview/hello-color-foreground-red.svg

Never mind.... and keep it up.

**Comment by monsieurbadia** [comment]
Hi Booze,

Thank you for your issue. It was not frugality but details. I appreciate 👌
I have just done a fix for this issue.

Cheers,
monsieurbadia
